# Use root/example as user/password credentials
version: '3.1'

services:

  streamlit_app:
    build: streamlit_app/
    restart: always
    ports:
      - 8502:8501
    volumes:
      - ./streamlit_app:/streamlit_app
      - ./pipeline:/pipeline
    depends_on:
      - mongo_db
      
  mongo_db:
    image: mongo:4.2.12
    environment:
      MONGO_INITDB_ROOT_USERNAME: abdessamad
      MONGO_INITDB_ROOT_PASSWORD: abdessamad
    ports:
      - 27017:27017
    volumes: 
      - ./data:/data/db
      
  resume_analysis_server:
    build: resume_analysis_server/
    restart: always
    ports:
      - 4200:4200
    volumes:
      - ./resume_analysis_server:/resume_analysis_server
      - ./pipeline:/pipeline
    depends_on:
      - mongo_db

  mongo_express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=abdessamad
      - ME_CONFIG_MONGODB_ADMINPASSWORD=abdessamad
      - ME_CONFIG_MONGODB_URL=mongodb://abdessamad:abdessamad@mongo_db:27017/
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - mongo_db

  chrome_node_1:
    image: selenium/node-chrome:4.7.2-20221219
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  chrome_node_2:
    image: selenium/node-chrome:4.7.2-20221219
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.7.2-20221219
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"